In [2]:
pip install pymssql && pip install mysql-connector && pip install pyodbc

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymssql in c:\users\ok\appdata\roaming\python\python311\site-packages (2.2.7)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql-connector in c:\users\ok\appdata\roaming\python\python311\site-packages (2.2.9)
Defaulting to user installation because normal site-packages is not writeable
Collecting pyodbc
  Downloading pyodbc-4.0.35-cp311-cp311-win_amd64.whl (66 kB)
     ---------------------------------------- 0.0/66.0 kB ? eta -:--:--
     ---------------------------------------- 66.0/66.0 kB 3.5 MB/s eta 0:00:00
Installing collected packages: pyodbc
Successfully installed pyodbc-4.0.35
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pymssql
import mysql.connector
import pyodbc
import uuid
from datetime import datetime, date, time, timezone
import re


print('Hora:' + str(datetime.now()))
print('iniciando')

# Conectar ao SQL Server
conn = pymssql.connect(server='169.57.163.38', user='cargaphone',
                       password='CP@SenhaForte#123', database='CargaPhone')
cursor = conn.cursor()

# Definir a quantidade de resultados por página e a página inicial
page_size = 100
page_num = 1

# Ler dados da tabela usuarios paginados

query = 'select [Ativo], [ID], [Nome], [Email], [Senha], [UnidadeID] FROM [CargaPhone].[dbo].[Usuario]'


cursor.execute(query)
usuarios = cursor.fetchall()

# Desconectar do SQL Server
conn.close()

# Conectar ao MySQL
# mydb = mysql.connector.connect(
#   host="us-cdbr-east-06.cleardb.net",
#   user="b4f8033d37e8e8",
#   password="c4f88825",
#   database="heroku_d67bbb63764a109"
# )
mydb = pyodbc.connect(
    'DRIVER={MySQL ODBC 8.0 ANSI Driver};User=b4f8033d37e8e8;Password=c4f88825;Server=us-cdbr-east-06.cleardb.net;Database=heroku_d67bbb63764a109;')
mycursor = mydb.cursor()

# Inserir dados na tabela users
loop = 1
for usuario in usuarios:
    # numero = 0

    # print(str(usuario[4]))
    #    print(str(usuario[4]))

    try:
       ativo = 1
       if usuario[0]:
        ativo = 1
       else:
        ativo = 0

    except AttributeError:
        usuario[4] = 1

    id_old = usuario[1]
    name = usuario[2]
    email = usuario[3]
    password = usuario[4]
    tenantId = usuario[5]
    id = uuid.uuid1()
    query = f"INSERT INTO users (id, ativo, id_old, name, email, password, tenant_id_old) VALUES ('{id}',{ativo}, {id_old}, '{name}', '{email}', '{password}', {tenantId})"
#     query = "INSERT INTO users (ativo, id_old, name, email, password, tenant_id_old) VALUES ("+ str(ativo) +", %s, %s, %s, %s, %s)"
#     print(query)
    mycursor.execute(query)
    # mydb.commit()
    print('Loop: ' + str(loop))
    loop += 1

# Confirmar as alterações no MySQL
mydb.commit()
print('Finalizado')

# Desconectar do MySQL
mydb.close()

Hora:2023-02-16 17:20:06.891069
iniciando
Loop: 1
Loop: 2
Loop: 3
Loop: 4
Loop: 5
Loop: 6
Loop: 7
Loop: 8
Loop: 9
Loop: 10
Loop: 11
Loop: 12
Loop: 13
Loop: 14
Loop: 15
Loop: 16
Loop: 17
Loop: 18
Loop: 19
Loop: 20
Loop: 21
Loop: 22
Loop: 23
Loop: 24
Loop: 25
Loop: 26
Loop: 27
Loop: 28
Loop: 29
Loop: 30
Loop: 31
Loop: 32
Loop: 33
Loop: 34
Loop: 35
Loop: 36
Loop: 37
Loop: 38
Loop: 39
Loop: 40
Loop: 41
Loop: 42
Loop: 43
Loop: 44
Loop: 45
Loop: 46
Loop: 47
Loop: 48
Loop: 49
Loop: 50
Loop: 51
Loop: 52
Loop: 53
Loop: 54
Loop: 55
Loop: 56
Loop: 57
Loop: 58
Loop: 59
Loop: 60
Loop: 61
Loop: 62
Loop: 63
Loop: 64
Loop: 65
Loop: 66
Loop: 67
Loop: 68
Loop: 69
Loop: 70
Loop: 71
Loop: 72
Loop: 73
Loop: 74
Loop: 75
Loop: 76
Loop: 77
Loop: 78
Loop: 79
Loop: 80
Loop: 81
Loop: 82
Loop: 83
Loop: 84
Loop: 85
Loop: 86
Loop: 87
Loop: 88
Loop: 89
Loop: 90
Loop: 91
Loop: 92
Loop: 93
Loop: 94
Loop: 95
Loop: 96
Loop: 97
Loop: 98
Loop: 99
Loop: 100
Loop: 101
Loop: 102
Loop: 103
Loop: 104
Loop: 105
Loop: 106
Loop: 107
Loop: 108
Loop: 109
Loop: 110
Loop: 111
Loop: 112
Loop: 113
Loop: 114
Loop: 115
Loop: 116
Loop: 117
Loop: 118
Loop: 119
Loop: 120
Loop: 121
Loop: 122
Loop: 123
Loop: 124
Loop: 125
Loop: 126
Loop: 127
Loop: 128
Loop: 129
Loop: 130
Loop: 131
Loop: 132
Loop: 133
Loop: 134
Loop: 135
Loop: 136
Loop: 137
Loop: 138
Loop: 139
Loop: 140
Loop: 141
Loop: 142
Loop: 143
Loop: 144
Loop: 145
Loop: 146
Loop: 147
Loop: 148
Loop: 149
Loop: 150
Loop: 151
Loop: 152
Loop: 153
Loop: 154
Loop: 155
Loop: 156
Loop: 157
Loop: 158
Loop: 159
Loop: 160
Loop: 161
Loop: 162
Loop: 163
Loop: 164
Loop: 165
Loop: 166
Loop: 167
Loop: 168
Loop: 169
Loop: 170
Loop: 171
Loop: 172
Loop: 173
Loop: 174
Loop: 175
Loop: 176
Loop: 177
Loop: 178
Loop: 179
Loop: 180
Loop: 181
Loop: 182
Loop: 183
Loop: 184
Loop: 185
Loop: 186
Loop: 187
Loop: 188
Loop: 189
Loop: 190
Loop: 191
Loop: 192
Loop: 193
Loop: 194
Loop: 195
Loop: 196
Loop: 197
Loop: 198
Loop: 199
Loop: 200
Loop: 201
Loop: 202
Loop: 203
Loop: 204
Loop: 205
Loop: 206
Loop: 207
Loop: 208
Loop: 209
Loop: 210
Loop: 211
Loop: 212
Loop: 213
Loop: 214
Loop: 215
Loop: 216
Loop: 217
Loop: 218
Loop: 219
Loop: 220
Loop: 221
Loop: 222
Loop: 223
Loop: 224
Loop: 225
Loop: 226
Loop: 227
Loop: 228
Loop: 229
Loop: 230
Loop: 231
Loop: 232
Loop: 233
Loop: 234
Loop: 235
Loop: 236
Loop: 237
Loop: 238
Loop: 239
Loop: 240
Loop: 241
Loop: 242
Loop: 243
Loop: 244
Loop: 245
Loop: 246
Finalizado